# Generated by Django 5.0.2 on 2024-03-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TaskCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=30)),
                ('taskDescription', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('Task_Assign_Date', models.DateTimeField()),
                ('category', models.ManyToManyField(to='TaskCategory.taskcategory')),
            ],
        ),
    ]
